//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1349008968_arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("_1349008968_arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1349008989_disk {
            get {
                object obj = ResourceManager.GetObject("_1349008989_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1349009007_Delete {
            get {
                object obj = ResourceManager.GetObject("_1349009007_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input valid task ID.
        /// </summary>
        internal static string Input_valid_task_ID {
            get {
                return ResourceManager.GetString("Input_valid_task_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;MTVContainer&quot;&gt;
        ///&lt;table  cellspacing=&quot;1&quot; cellpadding=&quot;3&quot; rules=&quot;all&quot; border=&quot;0&quot;   class=&quot;table_request&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;width:20%;font:12px Tahoma, Verdana, Arial, Helvetica, sans-serif;&quot; colspan=&quot;1&quot;  class=&quot;table_dark_row&quot;&gt;{DateTime}&lt;/td&gt;
        ///		&lt;td style=&quot;width:80%;font:12px Tahoma, Verdana, Arial, Helvetica, sans-serif;&quot; colspan=&quot;3&quot;  class=&quot;table_dark_row&quot;&gt;{FIO}&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;width:100%;font:12px Tahoma, Verdana, Arial, Helvetica, sans-serif;&quot; colspan=&quot;4&quot;&gt;{Text}&lt;/td&gt;
        ///	&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///.table_header
        ///{
        ///color:buttontext;
        ///background-color:buttonface;
        ///border-color:Black;
        ///font-size:Small;
        ///font-style:normal;
        ///white-space:nowrap;
        ///font:10px Tahoma, Verdana, Arial, Helvetica, sans-serif;}
        ///
        ///.table_request
        ///{
        ///font:12px Tahoma, Verdana, Arial, Helvetica, sans-serif;
        ///background-color:Black;
        ///border-color:Black;
        ///border-width:0px;
        ///border-style:Solid;
        ///width:98%;
        ///}
        ///
        ///.table_request td
        ///{
        ///color:Black;
        ///background-color:White;
        ///}
        ///
        ///.table_request td.table_dark_row
        ///{
        ///color:button [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
